server:
  servlet:
    context-path: /training
    encoding:
      charset: UTF-8
      enabled: true
  port: 8888
spring:
  application:
    name: noncom-info1-service
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
    url: jdbc:oracle:thin:@203.150.199.131:1521:XE
    username: JOBREPORT
    password: JOBREPORT
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-request-size: 250MB
      max-file-size: 2GB
logging:
  level:
      com.ss.training: debug